name: taski_to_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  auto_injector: ^2.1.0
  go_router: ^14.8.1
  result_dart: ^2.0.0
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
