name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  flutter-ci:
    name: CI - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3
          cache: true

      - name: Clean Flutter cache
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Run static analysis (lint)
        run: flutter analyze

      - name: Check code formatting
        run: |
          flutter format --dry-run --set-exit-if-changed lib/
          flutter format --dry-run --set-exit-if-changed test/

      - name: Run tests
        run: flutter test --coverage

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          flags: unittests
          name: flutter-codecov
          fail_ci_if_error: true